### PR TITLE
When creating a support user, default the locale to en_US

### PR DESCRIPTION
**Pull request by dchymko**
## Description
When we create a new VIP Support user, set their locale to en_US (rather than it using whatever the site default is set to)

Fixes: #82

### CODE REVIEW

**Comment by dchymko** [comment]
Not sure if we should check if the locale is installed first?

**Comment by GaryJones** [comment]
> Not sure if we should check if the locale is installed first?

What would happen if it's not?

Is English (US) installed on all sites by default anyway? Can it even be removed by clients>

**Comment by mjangda** [comment]
> Not sure if we should check if the locale is installed first?

It'd just fall back to the default.

**Comment by dchymko** [comment]
r138789-deploy

https://github.com/Automattic/vip-go-mu-plugins/pull/1242

**Pull request merged**
