### PR TITLE
Blacklist certain capabilities that conflict with the platform

### LINKED ISSUE #52: Don't provide blocked capabilities that no user should have
Some capabilities are tied to constants and shouldn't ever be provided, even to support users. For example, we define `DISALLOW_FILE_MODS`, which should strip all users of the `edit_files` capability. VIP Support users, however, are granted this capability.

A blacklist is probably sufficient, as there are a limited set of caps that no one should ever have.

### PR DESCRIPTION
**Pull request by ethitter**
Certain capabilities, such as those related to filesystem modifications, don't make sense for even VIP Support users, as the filesystem is read-only.

Fixes #52

### CODE REVIEW

**Comment by mjangda** [comment]
What happens when the filesystem is read-only and you have these caps?

**Comment by ethitter** [comment]
Nothing too serious, it mostly leads to confusion. Core displays the theme and plugin editors, even though they should be disabled for all users care of the `DISALLOW_FILE_MODS` constant. Themes/plugins that use the file editor (or check related caps) also provide VIP Support users with an inconsistent experience. This came about as there was some confusion while someone was reviewing a plugin that checked the `edit_files` cap, and it was unexpectedly returning `true`.

**Comment by mjangda** [comment]
Got it. (Also just caught up on the Slack scrollback :))

My only concern here would be that `user_has_cap` is fired a lot of times so we want to make sure it's super fast. I'm assuming that the cost of `array_diff` here is probably negligible.

**Comment by ethitter** [comment]
Yeah, I thought about that. I think the `array_diff()` is preferable to a check inside the `foreach()`, and at worst, we're only slowing this down for ourselves. :)

**Comment by scottsweb** [comment]
This caught me out too. I was looking at tumbleweed and noticed you can `delete` a plugin - or at least the UI suggests you can and started to implement changes for that: https://github.com/Automattic/vip-dashboard/pull/75/files#diff-89ad60d19282ec7bc4917b8a060268ccR388

**Pull request merged**
